import { type NextPage } from "next";
import Head from "next/head";

import { Header } from "@/components/Header";
import { Orders } from "@/components/Orders";
import { SideBar } from "@/components/SideBar";
import { GlobalContainer, ContentContainer } from "@/styles/GlobalStyles";

import HomeIcon from "@/assets/images/home.svg";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>spicywaiter</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SideBar />
      <GlobalContainer>
        <Header title="Home" subtitle="Acompanhe os pedidos dos clientes" icon={HomeIcon as string} />
        <ContentContainer>
          <Orders />
        </ContentContainer>
      </GlobalContainer>
    </>
  );
};

export default Home;

